#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""User_Identification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eK7K6z7xuzzGUqgGZ4m2DfpsvIAr-dVS

Installation and imports
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install git+https://github.com/speechbrain/speechbrain.git

import os
import torch
import torchaudio
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from speechbrain.inference.speaker import EncoderClassifier
from sklearn.model_selection import train_test_split

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Define the dataset class
class AtlasSpeakerDataset(Dataset):
    def __init__(self, file_paths, labels, augment=False, target_labels={1, 2, 3}, max_length=48000):
        self.file_paths = file_paths
        self.labels = labels
        self.augment = augment
        self.target_labels = target_labels
        self.max_length = max_length

    def __len__(self):
        return len(self.file_paths)

    def __getitem__(self, idx):
        waveform, sr = torchaudio.load(self.file_paths[idx])
        label = self.labels[idx]

        # Standard preprocessing (16kHz, Mono, Pad/Truncate)
        if sr != 16000:
            waveform = torchaudio.transforms.Resample(sr, 16000)(waveform)
        if waveform.shape[0] > 1:
            waveform = torch.mean(waveform, dim=0, keepdim=True)

        # Data Augmentation: Applied only to positive classes during training
        if self.augment and label in self.target_labels:
            # Random Noise
            if random.random() > 0.5:
                noise = torch.randn_like(waveform) * 0.005
                waveform = waveform + noise
            # Random Time Shift
            shift = random.randint(-4000, 4000)
            waveform = torch.roll(waveform, shifts=shift, dims=1)

        if waveform.shape[1] > self.max_length:
            waveform = waveform[:, :self.max_length]
        else:
            waveform = torch.nn.functional.pad(waveform, (0, self.max_length - waveform.shape[1]))

        return waveform.squeeze(0), label

# Load the pre-trained model from HuggingFace/SpeechBrain
classifier = EncoderClassifier.from_hparams(
    source="speechbrain/spkrec-ecapa-voxceleb",
    run_opts={"device": str(device)}
)

# We only need the embedding extractor part
embedding_model = classifier.mods.embedding_model
embedding_model.to(device)

# Freeze the pre-trained weights to prevent overfitting the small dataset
for param in embedding_model.parameters():
    param.requires_grad = False

# Add a classification head to perform PEFT
class AtlasVerificationModel(nn.Module):
    def __init__(self, embedding_model, num_classes=4):
        super().__init__()
        self.embedding_model = embedding_model
        # ECAPA-TDNN outputs a 192-d embedding by default
        self.fc = nn.Sequential(
            nn.Linear(192, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        # Extract embeddings (Batch, 1, 192)
        embeddings = self.embedding_model(x)
        # Squeeze the middle dimension (Batch, 192)
        embeddings = embeddings.squeeze(1)
        # Classify
        out = self.fc(embeddings)
        return out

model = AtlasVerificationModel(embedding_model, num_classes=4).to(device)

"""Load pretrained model or train again from scratch"""

def load_atlas_model(path, embedding_model, device):

    checkpoint = torch.load(path, map_location=device)
    num_classes = checkpoint['num_classes']

    # Create the model skeleton
    loaded_model = AtlasVerificationModel(embedding_model, num_classes=num_classes)

    # Load the weights
    loaded_model.load_state_dict(checkpoint['model_state_dict'])
    loaded_model.to(device)
    loaded_model.eval() # Set to evaluation mode

    print(f"Model loaded successfully from {path}")
    return loaded_model

MODEL_SAVE_PATH = "/content/drive/MyDrive/Morning-Virtual-Assistant/User_verification_model.pth"

model = load_atlas_model(MODEL_SAVE_PATH, embedding_model, device)